/**
 * Permission Catalog — Single source of truth for all system permissions.
 * ~365 permissions across 6 modules, 512-bit bitset (64 bytes).
 * Append-only: bits are never reused. ADMINISTRATOR is pinned at bit 511.
 */

export interface PermissionDef {
  key: string;
  bit: number;
  module: ModuleId;
  submodule: string;
  action: string;
  label: string;
  description: string;
  dangerous?: boolean;
  implies?: string[];
}

export type ModuleId =
  | "INVENTORY"
  | "SALES"
  | "CRM"
  | "WEBSITE"
  | "REPORTS"
  | "SETTINGS";

// ─────────────────────────────────────────────────────────────────────────────
// INVENTORY MODULE (Bits 0–71)
// ─────────────────────────────────────────────────────────────────────────────

const INVENTORY_PRODUCTS = [
  {
    key: "INVENTORY.PRODUCTS.VIEW",
    bit: 0,
    module: "INVENTORY" as const,
    submodule: "Products",
    action: "VIEW",
    label: "View products",
    description: "See the product catalog and individual product pages.",
  },
  {
    key: "INVENTORY.PRODUCTS.CREATE",
    bit: 1,
    module: "INVENTORY" as const,
    submodule: "Products",
    action: "CREATE",
    label: "Create products",
    implies: ["INVENTORY.PRODUCTS.VIEW"],
    description:
      "Add new products to the catalog, including variants and images.",
  },
  {
    key: "INVENTORY.PRODUCTS.UPDATE",
    bit: 2,
    module: "INVENTORY" as const,
    submodule: "Products",
    action: "UPDATE",
    label: "Edit products",
    implies: ["INVENTORY.PRODUCTS.VIEW"],
    description:
      "Modify product details: name, price, stock levels, attributes.",
  },
  {
    key: "INVENTORY.PRODUCTS.DELETE",
    bit: 3,
    module: "INVENTORY" as const,
    submodule: "Products",
    action: "DELETE",
    label: "Delete products",
    dangerous: true,
    implies: ["INVENTORY.PRODUCTS.VIEW"],
    description: "Move products to trash. Soft-delete; restorable for 30 days.",
  },
  {
    key: "INVENTORY.PRODUCTS.IMPORT",
    bit: 4,
    module: "INVENTORY" as const,
    submodule: "Products",
    action: "IMPORT",
    label: "Import products via CSV",
    description: "Bulk-upload products from a CSV file.",
  },
  {
    key: "INVENTORY.PRODUCTS.EXPORT",
    bit: 5,
    module: "INVENTORY" as const,
    submodule: "Products",
    action: "EXPORT",
    label: "Export product catalog",
    description: "Download the full product list as CSV or Excel.",
  },
  {
    key: "INVENTORY.PRODUCTS.ADJUST_STOCK",
    bit: 6,
    module: "INVENTORY" as const,
    submodule: "Products",
    action: "ADJUST_STOCK",
    label: "Adjust stock levels",
    description: "Manually increase or decrease on-hand stock for any product.",
  },
] as const;

const INVENTORY_CATEGORIES = [
  {
    key: "INVENTORY.CATEGORIES.VIEW",
    bit: 7,
    module: "INVENTORY" as const,
    submodule: "Categories",
    action: "VIEW",
    label: "View categories",
    description: "See product categories and category pages.",
  },
  {
    key: "INVENTORY.CATEGORIES.CREATE",
    bit: 8,
    module: "INVENTORY" as const,
    submodule: "Categories",
    action: "CREATE",
    label: "Create categories",
    implies: ["INVENTORY.CATEGORIES.VIEW"],
    description: "Add new product categories.",
  },
  {
    key: "INVENTORY.CATEGORIES.UPDATE",
    bit: 9,
    module: "INVENTORY" as const,
    submodule: "Categories",
    action: "UPDATE",
    label: "Edit categories",
    implies: ["INVENTORY.CATEGORIES.VIEW"],
    description: "Modify category names, descriptions, and settings.",
  },
  {
    key: "INVENTORY.CATEGORIES.DELETE",
    bit: 10,
    module: "INVENTORY" as const,
    submodule: "Categories",
    action: "DELETE",
    label: "Delete categories",
    dangerous: true,
    implies: ["INVENTORY.CATEGORIES.VIEW"],
    description: "Move categories to trash.",
  },
] as const;

const INVENTORY_VENDORS = [
  {
    key: "INVENTORY.VENDORS.VIEW",
    bit: 11,
    module: "INVENTORY" as const,
    submodule: "Vendors",
    action: "VIEW",
    label: "View vendors",
    description: "See vendor list and vendor pages.",
  },
  {
    key: "INVENTORY.VENDORS.CREATE",
    bit: 12,
    module: "INVENTORY" as const,
    submodule: "Vendors",
    action: "CREATE",
    label: "Create vendors",
    implies: ["INVENTORY.VENDORS.VIEW"],
    description: "Add new vendors.",
  },
  {
    key: "INVENTORY.VENDORS.UPDATE",
    bit: 13,
    module: "INVENTORY" as const,
    submodule: "Vendors",
    action: "UPDATE",
    label: "Edit vendors",
    implies: ["INVENTORY.VENDORS.VIEW"],
    description: "Modify vendor details.",
  },
  {
    key: "INVENTORY.VENDORS.DELETE",
    bit: 14,
    module: "INVENTORY" as const,
    submodule: "Vendors",
    action: "DELETE",
    label: "Delete vendors",
    dangerous: true,
    implies: ["INVENTORY.VENDORS.VIEW"],
    description: "Move vendors to trash.",
  },
  {
    key: "INVENTORY.VENDORS.MANAGE_PAYMENTS",
    bit: 15,
    module: "INVENTORY" as const,
    submodule: "Vendors",
    action: "MANAGE_PAYMENTS",
    label: "Record vendor payments",
    dangerous: true,
    implies: ["INVENTORY.VENDORS.VIEW"],
    description: "Mark vendor invoices as paid; affects accounting.",
  },
] as const;

const INVENTORY_LOCATIONS = [
  {
    key: "INVENTORY.LOCATIONS.VIEW",
    bit: 16,
    module: "INVENTORY" as const,
    submodule: "Locations",
    action: "VIEW",
    label: "View locations",
    description: "See warehouse/store locations and their inventory levels.",
  },
  {
    key: "INVENTORY.LOCATIONS.CREATE",
    bit: 17,
    module: "INVENTORY" as const,
    submodule: "Locations",
    action: "CREATE",
    label: "Create locations",
    implies: ["INVENTORY.LOCATIONS.VIEW"],
    description: "Add new warehouse or store locations.",
  },
  {
    key: "INVENTORY.LOCATIONS.UPDATE",
    bit: 18,
    module: "INVENTORY" as const,
    submodule: "Locations",
    action: "UPDATE",
    label: "Edit locations",
    implies: ["INVENTORY.LOCATIONS.VIEW"],
    description: "Modify location details like address and contact info.",
  },
  {
    key: "INVENTORY.LOCATIONS.DELETE",
    bit: 19,
    module: "INVENTORY" as const,
    submodule: "Locations",
    action: "DELETE",
    label: "Delete locations",
    dangerous: true,
    implies: ["INVENTORY.LOCATIONS.VIEW"],
    description: "Move locations to trash.",
  },
  {
    key: "INVENTORY.LOCATIONS.SET_DEFAULT",
    bit: 20,
    module: "INVENTORY" as const,
    submodule: "Locations",
    action: "SET_DEFAULT",
    label: "Set default location",
    implies: ["INVENTORY.LOCATIONS.VIEW"],
    description: "Choose which location is used for new sales by default.",
  },
] as const;

const INVENTORY_TRANSFERS = [
  {
    key: "INVENTORY.TRANSFERS.VIEW",
    bit: 21,
    module: "INVENTORY" as const,
    submodule: "Transfers",
    action: "VIEW",
    label: "View stock transfers",
    description: "See stock transfers between locations.",
  },
  {
    key: "INVENTORY.TRANSFERS.CREATE",
    bit: 22,
    module: "INVENTORY" as const,
    submodule: "Transfers",
    action: "CREATE",
    label: "Create stock transfers",
    implies: ["INVENTORY.TRANSFERS.VIEW"],
    description: "Initiate a transfer of stock from one location to another.",
  },
  {
    key: "INVENTORY.TRANSFERS.APPROVE",
    bit: 23,
    module: "INVENTORY" as const,
    submodule: "Transfers",
    action: "APPROVE",
    label: "Approve transfers",
    implies: ["INVENTORY.TRANSFERS.VIEW"],
    description:
      "Approve pending transfers so they can be shipped. Required before stock leaves the source location.",
  },
  {
    key: "INVENTORY.TRANSFERS.REJECT",
    bit: 24,
    module: "INVENTORY" as const,
    submodule: "Transfers",
    action: "REJECT",
    label: "Reject transfers",
    implies: ["INVENTORY.TRANSFERS.VIEW"],
    description:
      "Reject a pending transfer with a reason; stock stays at source.",
  },
  {
    key: "INVENTORY.TRANSFERS.RECEIVE",
    bit: 25,
    module: "INVENTORY" as const,
    submodule: "Transfers",
    action: "RECEIVE",
    label: "Receive transfers at destination",
    implies: ["INVENTORY.TRANSFERS.VIEW"],
    description:
      "Confirm goods received at destination; commits stock movement.",
  },
  {
    key: "INVENTORY.TRANSFERS.REVERT",
    bit: 26,
    module: "INVENTORY" as const,
    submodule: "Transfers",
    action: "REVERT",
    label: "Revert completed transfers",
    dangerous: true,
    implies: ["INVENTORY.TRANSFERS.VIEW"],
    description:
      "Undo a completed transfer. Used only to fix mistakes; creates an audit trail.",
  },
  {
    key: "INVENTORY.TRANSFERS.DELETE",
    bit: 27,
    module: "INVENTORY" as const,
    submodule: "Transfers",
    action: "DELETE",
    label: "Delete draft transfers",
    implies: ["INVENTORY.TRANSFERS.VIEW"],
    description: "Delete a transfer that has not yet been approved.",
  },
] as const;

const INVENTORY_BUNDLES = [
  {
    key: "INVENTORY.BUNDLES.VIEW",
    bit: 28,
    module: "INVENTORY" as const,
    submodule: "Bundles",
    action: "VIEW",
    label: "View bundles",
    description: "See product bundles.",
  },
  {
    key: "INVENTORY.BUNDLES.CREATE",
    bit: 29,
    module: "INVENTORY" as const,
    submodule: "Bundles",
    action: "CREATE",
    label: "Create bundles",
    implies: ["INVENTORY.BUNDLES.VIEW"],
    description: "Create new product bundles.",
  },
  {
    key: "INVENTORY.BUNDLES.UPDATE",
    bit: 30,
    module: "INVENTORY" as const,
    submodule: "Bundles",
    action: "UPDATE",
    label: "Edit bundles",
    implies: ["INVENTORY.BUNDLES.VIEW"],
    description: "Modify bundle contents and pricing.",
  },
  {
    key: "INVENTORY.BUNDLES.DELETE",
    bit: 31,
    module: "INVENTORY" as const,
    submodule: "Bundles",
    action: "DELETE",
    label: "Delete bundles",
    dangerous: true,
    implies: ["INVENTORY.BUNDLES.VIEW"],
    description: "Remove bundles.",
  },
  {
    key: "INVENTORY.BUNDLES.PUBLISH",
    bit: 32,
    module: "INVENTORY" as const,
    submodule: "Bundles",
    action: "PUBLISH",
    label: "Publish bundles",
    implies: ["INVENTORY.BUNDLES.VIEW"],
    description: "Make bundles available for sale.",
  },
] as const;

const INVENTORY_GIFT_CARDS = [
  {
    key: "INVENTORY.GIFT_CARDS.VIEW",
    bit: 33,
    module: "INVENTORY" as const,
    submodule: "Gift Cards",
    action: "VIEW",
    label: "View gift cards",
    description: "See gift card inventory and transactions.",
  },
  {
    key: "INVENTORY.GIFT_CARDS.CREATE",
    bit: 34,
    module: "INVENTORY" as const,
    submodule: "Gift Cards",
    action: "CREATE",
    label: "Create gift cards",
    implies: ["INVENTORY.GIFT_CARDS.VIEW"],
    description: "Create new gift card batches.",
  },
  {
    key: "INVENTORY.GIFT_CARDS.UPDATE",
    bit: 35,
    module: "INVENTORY" as const,
    submodule: "Gift Cards",
    action: "UPDATE",
    label: "Edit gift cards",
    implies: ["INVENTORY.GIFT_CARDS.VIEW"],
    description: "Modify gift card details.",
  },
  {
    key: "INVENTORY.GIFT_CARDS.DELETE",
    bit: 36,
    module: "INVENTORY" as const,
    submodule: "Gift Cards",
    action: "DELETE",
    label: "Delete gift cards",
    dangerous: true,
    implies: ["INVENTORY.GIFT_CARDS.VIEW"],
    description: "Remove gift cards from inventory.",
  },
  {
    key: "INVENTORY.GIFT_CARDS.ISSUE",
    bit: 37,
    module: "INVENTORY" as const,
    submodule: "Gift Cards",
    action: "ISSUE",
    label: "Issue gift cards",
    implies: ["INVENTORY.GIFT_CARDS.VIEW"],
    description: "Distribute gift cards to customers.",
  },
  {
    key: "INVENTORY.GIFT_CARDS.REDEEM",
    bit: 38,
    module: "INVENTORY" as const,
    submodule: "Gift Cards",
    action: "REDEEM",
    label: "Redeem gift cards",
    implies: ["INVENTORY.GIFT_CARDS.VIEW"],
    description: "Apply gift card balances to sales.",
  },
  {
    key: "INVENTORY.GIFT_CARDS.VOID",
    bit: 39,
    module: "INVENTORY" as const,
    submodule: "Gift Cards",
    action: "VOID",
    label: "Void gift cards",
    dangerous: true,
    implies: ["INVENTORY.GIFT_CARDS.VIEW"],
    description: "Cancel or deactivate gift cards.",
  },
] as const;

const INVENTORY_PROMOS = [
  {
    key: "INVENTORY.PROMOS.VIEW",
    bit: 40,
    module: "INVENTORY" as const,
    submodule: "Promos",
    action: "VIEW",
    label: "View promos",
    description: "See promotional campaigns and offers.",
  },
  {
    key: "INVENTORY.PROMOS.CREATE",
    bit: 41,
    module: "INVENTORY" as const,
    submodule: "Promos",
    action: "CREATE",
    label: "Create promos",
    implies: ["INVENTORY.PROMOS.VIEW"],
    description: "Create new promotional campaigns.",
  },
  {
    key: "INVENTORY.PROMOS.UPDATE",
    bit: 42,
    module: "INVENTORY" as const,
    submodule: "Promos",
    action: "UPDATE",
    label: "Edit promos",
    implies: ["INVENTORY.PROMOS.VIEW"],
    description: "Modify promo details and rules.",
  },
  {
    key: "INVENTORY.PROMOS.DELETE",
    bit: 43,
    module: "INVENTORY" as const,
    submodule: "Promos",
    action: "DELETE",
    label: "Delete promos",
    dangerous: true,
    implies: ["INVENTORY.PROMOS.VIEW"],
    description: "Remove promotional campaigns.",
  },
  {
    key: "INVENTORY.PROMOS.PUBLISH",
    bit: 44,
    module: "INVENTORY" as const,
    submodule: "Promos",
    action: "PUBLISH",
    label: "Publish promos",
    implies: ["INVENTORY.PROMOS.VIEW"],
    description: "Make promos active and available.",
  },
  {
    key: "INVENTORY.PROMOS.END",
    bit: 45,
    module: "INVENTORY" as const,
    submodule: "Promos",
    action: "END",
    label: "End promos",
    implies: ["INVENTORY.PROMOS.VIEW"],
    description: "Deactivate promotional campaigns.",
  },
] as const;

const INVENTORY_COLLECTIONS = [
  {
    key: "INVENTORY.COLLECTIONS.VIEW",
    bit: 46,
    module: "INVENTORY" as const,
    submodule: "Collections",
    action: "VIEW",
    label: "View collections",
    description: "See product collections and groupings.",
  },
  {
    key: "INVENTORY.COLLECTIONS.CREATE",
    bit: 47,
    module: "INVENTORY" as const,
    submodule: "Collections",
    action: "CREATE",
    label: "Create collections",
    implies: ["INVENTORY.COLLECTIONS.VIEW"],
    description: "Create new product collections.",
  },
  {
    key: "INVENTORY.COLLECTIONS.UPDATE",
    bit: 48,
    module: "INVENTORY" as const,
    submodule: "Collections",
    action: "UPDATE",
    label: "Edit collections",
    implies: ["INVENTORY.COLLECTIONS.VIEW"],
    description: "Modify collection contents and metadata.",
  },
  {
    key: "INVENTORY.COLLECTIONS.DELETE",
    bit: 49,
    module: "INVENTORY" as const,
    submodule: "Collections",
    action: "DELETE",
    label: "Delete collections",
    dangerous: true,
    implies: ["INVENTORY.COLLECTIONS.VIEW"],
    description: "Remove product collections.",
  },
  {
    key: "INVENTORY.COLLECTIONS.REORDER",
    bit: 50,
    module: "INVENTORY" as const,
    submodule: "Collections",
    action: "REORDER",
    label: "Reorder collections",
    implies: ["INVENTORY.COLLECTIONS.VIEW"],
    description: "Change the order of items within collections.",
  },
] as const;

const INVENTORY_ATTRIBUTE_TYPES = [
  {
    key: "INVENTORY.ATTRIBUTE_TYPES.VIEW",
    bit: 51,
    module: "INVENTORY" as const,
    submodule: "Attribute Types",
    action: "VIEW",
    label: "View attribute types",
    description: "See product attribute definitions.",
  },
  {
    key: "INVENTORY.ATTRIBUTE_TYPES.CREATE",
    bit: 52,
    module: "INVENTORY" as const,
    submodule: "Attribute Types",
    action: "CREATE",
    label: "Create attribute types",
    implies: ["INVENTORY.ATTRIBUTE_TYPES.VIEW"],
    description: "Define new product attributes.",
  },
  {
    key: "INVENTORY.ATTRIBUTE_TYPES.UPDATE",
    bit: 53,
    module: "INVENTORY" as const,
    submodule: "Attribute Types",
    action: "UPDATE",
    label: "Edit attribute types",
    implies: ["INVENTORY.ATTRIBUTE_TYPES.VIEW"],
    description: "Modify product attribute definitions.",
  },
  {
    key: "INVENTORY.ATTRIBUTE_TYPES.DELETE",
    bit: 54,
    module: "INVENTORY" as const,
    submodule: "Attribute Types",
    action: "DELETE",
    label: "Delete attribute types",
    dangerous: true,
    implies: ["INVENTORY.ATTRIBUTE_TYPES.VIEW"],
    description: "Remove product attribute definitions.",
  },
] as const;

const INVENTORY_DISCOUNTS = [
  {
    key: "INVENTORY.DISCOUNTS.VIEW",
    bit: 55,
    module: "INVENTORY" as const,
    submodule: "Discounts",
    action: "VIEW",
    label: "View discounts",
    description: "See discount rules and pricing.",
  },
  {
    key: "INVENTORY.DISCOUNTS.CREATE",
    bit: 56,
    module: "INVENTORY" as const,
    submodule: "Discounts",
    action: "CREATE",
    label: "Create discounts",
    implies: ["INVENTORY.DISCOUNTS.VIEW"],
    description: "Create new discount rules.",
  },
  {
    key: "INVENTORY.DISCOUNTS.UPDATE",
    bit: 57,
    module: "INVENTORY" as const,
    submodule: "Discounts",
    action: "UPDATE",
    label: "Edit discounts",
    implies: ["INVENTORY.DISCOUNTS.VIEW"],
    description: "Modify discount rules.",
  },
  {
    key: "INVENTORY.DISCOUNTS.DELETE",
    bit: 58,
    module: "INVENTORY" as const,
    submodule: "Discounts",
    action: "DELETE",
    label: "Delete discounts",
    dangerous: true,
    implies: ["INVENTORY.DISCOUNTS.VIEW"],
    description: "Remove discount rules.",
  },
  {
    key: "INVENTORY.DISCOUNTS.APPROVE_OVERRIDE",
    bit: 59,
    module: "INVENTORY" as const,
    submodule: "Discounts",
    action: "APPROVE_OVERRIDE",
    label: "Approve discount overrides",
    implies: ["INVENTORY.DISCOUNTS.VIEW"],
    description: "Approve discounts that exceed automatic limits.",
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// SALES MODULE (Bits 60–119)
// ─────────────────────────────────────────────────────────────────────────────

const SALES_SALES = [
  {
    key: "SALES.SALES.VIEW",
    bit: 60,
    module: "SALES" as const,
    submodule: "Sales",
    action: "VIEW",
    label: "View sales",
    description: "See sales list and individual sale pages.",
  },
  {
    key: "SALES.SALES.VIEW_OWN_ONLY",
    bit: 61,
    module: "SALES" as const,
    submodule: "Sales",
    action: "VIEW_OWN_ONLY",
    label: "View only own sales",
    description:
      "Restricts the user to seeing sales they personally created. Combine with SALES.SALES.VIEW for full access.",
  },
  {
    key: "SALES.SALES.CREATE",
    bit: 62,
    module: "SALES" as const,
    submodule: "Sales",
    action: "CREATE",
    label: "Create sales",
    implies: ["SALES.SALES.VIEW"],
    description: "Create new sales and transactions.",
  },
  {
    key: "SALES.SALES.EDIT_AFTER_FINALIZE",
    bit: 63,
    module: "SALES" as const,
    submodule: "Sales",
    action: "EDIT_AFTER_FINALIZE",
    label: "Edit finalized sales",
    dangerous: true,
    implies: ["SALES.SALES.VIEW"],
    description: "Modify a sale after it has been finalized. Affects reports.",
  },
  {
    key: "SALES.SALES.DELETE",
    bit: 64,
    module: "SALES" as const,
    submodule: "Sales",
    action: "DELETE",
    label: "Delete sales",
    dangerous: true,
    implies: ["SALES.SALES.VIEW"],
    description: "Move sales to trash.",
  },
  {
    key: "SALES.SALES.REFUND",
    bit: 65,
    module: "SALES" as const,
    submodule: "Sales",
    action: "REFUND",
    label: "Issue refunds",
    dangerous: true,
    implies: ["SALES.SALES.VIEW"],
    description: "Process refunds and return payments.",
  },
  {
    key: "SALES.SALES.VOID",
    bit: 66,
    module: "SALES" as const,
    submodule: "Sales",
    action: "VOID",
    label: "Void sales",
    dangerous: true,
    implies: ["SALES.SALES.VIEW"],
    description: "Void a completed sale.",
  },
  {
    key: "SALES.SALES.APPROVE_DISCOUNT",
    bit: 67,
    module: "SALES" as const,
    submodule: "Sales",
    action: "APPROVE_DISCOUNT",
    label: "Approve sale-line discounts",
    implies: ["SALES.SALES.VIEW"],
    description: "Some discounts above a threshold require manager approval.",
  },
  {
    key: "SALES.SALES.EXPORT",
    bit: 68,
    module: "SALES" as const,
    submodule: "Sales",
    action: "EXPORT",
    label: "Export sales",
    description: "Download sales data as CSV or Excel.",
  },
] as const;

const SALES_WEBSITE_ORDERS = [
  {
    key: "SALES.WEBSITE_ORDERS.VIEW",
    bit: 69,
    module: "SALES" as const,
    submodule: "Website Orders",
    action: "VIEW",
    label: "View website orders",
    description: "See orders placed via the website.",
  },
  {
    key: "SALES.WEBSITE_ORDERS.VERIFY",
    bit: 70,
    module: "SALES" as const,
    submodule: "Website Orders",
    action: "VERIFY",
    label: "Verify website orders",
    implies: ["SALES.WEBSITE_ORDERS.VIEW"],
    description: "Verify and process website orders.",
  },
  {
    key: "SALES.WEBSITE_ORDERS.REJECT",
    bit: 71,
    module: "SALES" as const,
    submodule: "Website Orders",
    action: "REJECT",
    label: "Reject website orders",
    implies: ["SALES.WEBSITE_ORDERS.VIEW"],
    description: "Reject website orders with a reason.",
  },
  {
    key: "SALES.WEBSITE_ORDERS.CONVERT",
    bit: 72,
    module: "SALES" as const,
    submodule: "Website Orders",
    action: "CONVERT",
    label: "Convert website order to sale",
    implies: ["SALES.WEBSITE_ORDERS.VIEW"],
    description: "Convert a website order into a formal sale.",
  },
  {
    key: "SALES.WEBSITE_ORDERS.EXPORT",
    bit: 73,
    module: "SALES" as const,
    submodule: "Website Orders",
    action: "EXPORT",
    label: "Export website orders",
    description: "Download website order data.",
  },
] as const;

const SALES_ABANDONED_CARTS = [
  {
    key: "SALES.ABANDONED_CARTS.VIEW",
    bit: 74,
    module: "SALES" as const,
    submodule: "Abandoned Carts",
    action: "VIEW",
    label: "View abandoned carts",
    description: "See shopping carts that were abandoned by customers.",
  },
  {
    key: "SALES.ABANDONED_CARTS.SEND_RECOVERY_EMAIL",
    bit: 75,
    module: "SALES" as const,
    submodule: "Abandoned Carts",
    action: "SEND_RECOVERY_EMAIL",
    label: "Send cart recovery emails",
    implies: ["SALES.ABANDONED_CARTS.VIEW"],
    description:
      "Send recovery emails to encourage customers to complete their purchase.",
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// CRM MODULE (Bits 76–230)
// ─────────────────────────────────────────────────────────────────────────────

const CRM_CONTACTS = [
  {
    key: "CRM.CONTACTS.VIEW",
    bit: 76,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "VIEW",
    label: "View contacts",
    description: "See contact list and profiles.",
  },
  {
    key: "CRM.CONTACTS.VIEW_OWN_ONLY",
    bit: 77,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "VIEW_OWN_ONLY",
    label: "View only own contacts",
    description: "See only contacts assigned to the user.",
  },
  {
    key: "CRM.CONTACTS.CREATE",
    bit: 78,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "CREATE",
    label: "Create contacts",
    implies: ["CRM.CONTACTS.VIEW"],
    description: "Add new contacts.",
  },
  {
    key: "CRM.CONTACTS.UPDATE",
    bit: 79,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "UPDATE",
    label: "Edit contacts",
    implies: ["CRM.CONTACTS.VIEW"],
    description: "Modify contact details.",
  },
  {
    key: "CRM.CONTACTS.DELETE",
    bit: 80,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "DELETE",
    label: "Delete contacts",
    dangerous: true,
    implies: ["CRM.CONTACTS.VIEW"],
    description: "Move contacts to trash.",
  },
  {
    key: "CRM.CONTACTS.IMPORT",
    bit: 81,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "IMPORT",
    label: "Import contacts",
    description: "Bulk upload contacts from CSV.",
  },
  {
    key: "CRM.CONTACTS.EXPORT",
    bit: 82,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "EXPORT",
    label: "Export contacts",
    description: "Download contact data as CSV or Excel.",
  },
  {
    key: "CRM.CONTACTS.MERGE",
    bit: 83,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "MERGE",
    label: "Merge contacts",
    implies: ["CRM.CONTACTS.VIEW"],
    description: "Combine duplicate contact records.",
  },
  {
    key: "CRM.CONTACTS.EXPORT_PII",
    bit: 84,
    module: "CRM" as const,
    submodule: "Contacts",
    action: "EXPORT_PII",
    label: "Export contact PII",
    dangerous: true,
    implies: ["CRM.CONTACTS.VIEW"],
    description: "Export personal identifying information.",
  },
] as const;

const CRM_COMPANIES = [
  {
    key: "CRM.COMPANIES.VIEW",
    bit: 85,
    module: "CRM" as const,
    submodule: "Companies",
    action: "VIEW",
    label: "View companies",
    description: "See company list and profiles.",
  },
  {
    key: "CRM.COMPANIES.CREATE",
    bit: 86,
    module: "CRM" as const,
    submodule: "Companies",
    action: "CREATE",
    label: "Create companies",
    implies: ["CRM.COMPANIES.VIEW"],
    description: "Add new companies.",
  },
  {
    key: "CRM.COMPANIES.UPDATE",
    bit: 87,
    module: "CRM" as const,
    submodule: "Companies",
    action: "UPDATE",
    label: "Edit companies",
    implies: ["CRM.COMPANIES.VIEW"],
    description: "Modify company details.",
  },
  {
    key: "CRM.COMPANIES.DELETE",
    bit: 88,
    module: "CRM" as const,
    submodule: "Companies",
    action: "DELETE",
    label: "Delete companies",
    dangerous: true,
    implies: ["CRM.COMPANIES.VIEW"],
    description: "Move companies to trash.",
  },
  {
    key: "CRM.COMPANIES.EXPORT",
    bit: 89,
    module: "CRM" as const,
    submodule: "Companies",
    action: "EXPORT",
    label: "Export companies",
    description: "Download company data.",
  },
] as const;

const CRM_LEADS = [
  {
    key: "CRM.LEADS.VIEW",
    bit: 90,
    module: "CRM" as const,
    submodule: "Leads",
    action: "VIEW",
    label: "View leads",
    description: "See lead list and details.",
  },
  {
    key: "CRM.LEADS.VIEW_OWN_ONLY",
    bit: 91,
    module: "CRM" as const,
    submodule: "Leads",
    action: "VIEW_OWN_ONLY",
    label: "View only own leads",
    description: "See only leads assigned to the user.",
  },
  {
    key: "CRM.LEADS.CREATE",
    bit: 92,
    module: "CRM" as const,
    submodule: "Leads",
    action: "CREATE",
    label: "Create leads",
    implies: ["CRM.LEADS.VIEW"],
    description: "Add new leads.",
  },
  {
    key: "CRM.LEADS.UPDATE",
    bit: 93,
    module: "CRM" as const,
    submodule: "Leads",
    action: "UPDATE",
    label: "Edit leads",
    implies: ["CRM.LEADS.VIEW"],
    description: "Modify lead details.",
  },
  {
    key: "CRM.LEADS.DELETE",
    bit: 94,
    module: "CRM" as const,
    submodule: "Leads",
    action: "DELETE",
    label: "Delete leads",
    dangerous: true,
    implies: ["CRM.LEADS.VIEW"],
    description: "Move leads to trash.",
  },
  {
    key: "CRM.LEADS.CONVERT",
    bit: 95,
    module: "CRM" as const,
    submodule: "Leads",
    action: "CONVERT",
    label: "Convert leads to contacts",
    implies: ["CRM.LEADS.VIEW"],
    description: "Convert a lead into a customer contact.",
  },
  {
    key: "CRM.LEADS.ASSIGN",
    bit: 96,
    module: "CRM" as const,
    submodule: "Leads",
    action: "ASSIGN",
    label: "Assign leads",
    implies: ["CRM.LEADS.VIEW"],
    description: "Assign leads to team members.",
  },
  {
    key: "CRM.LEADS.EXPORT",
    bit: 97,
    module: "CRM" as const,
    submodule: "Leads",
    action: "EXPORT",
    label: "Export leads",
    description: "Download lead data.",
  },
] as const;

const CRM_DEALS = [
  {
    key: "CRM.DEALS.VIEW",
    bit: 98,
    module: "CRM" as const,
    submodule: "Deals",
    action: "VIEW",
    label: "View deals",
    description: "See deal list and pipeline.",
  },
  {
    key: "CRM.DEALS.VIEW_OWN_ONLY",
    bit: 99,
    module: "CRM" as const,
    submodule: "Deals",
    action: "VIEW_OWN_ONLY",
    label: "View only own deals",
    description: "See only deals assigned to the user.",
  },
  {
    key: "CRM.DEALS.CREATE",
    bit: 100,
    module: "CRM" as const,
    submodule: "Deals",
    action: "CREATE",
    label: "Create deals",
    implies: ["CRM.DEALS.VIEW"],
    description: "Create new deals.",
  },
  {
    key: "CRM.DEALS.UPDATE",
    bit: 101,
    module: "CRM" as const,
    submodule: "Deals",
    action: "UPDATE",
    label: "Edit deals",
    implies: ["CRM.DEALS.VIEW"],
    description: "Modify deal details.",
  },
  {
    key: "CRM.DEALS.DELETE",
    bit: 102,
    module: "CRM" as const,
    submodule: "Deals",
    action: "DELETE",
    label: "Delete deals",
    dangerous: true,
    implies: ["CRM.DEALS.VIEW"],
    description: "Move deals to trash.",
  },
  {
    key: "CRM.DEALS.ASSIGN",
    bit: 103,
    module: "CRM" as const,
    submodule: "Deals",
    action: "ASSIGN",
    label: "Assign deals",
    implies: ["CRM.DEALS.VIEW"],
    description: "Assign deals to team members.",
  },
  {
    key: "CRM.DEALS.CHANGE_STAGE",
    bit: 104,
    module: "CRM" as const,
    submodule: "Deals",
    action: "CHANGE_STAGE",
    label: "Move deals between stages",
    implies: ["CRM.DEALS.VIEW"],
    description: "Change a deal status in the pipeline.",
  },
  {
    key: "CRM.DEALS.CHANGE_VALUE",
    bit: 105,
    module: "CRM" as const,
    submodule: "Deals",
    action: "CHANGE_VALUE",
    label: "Change deal value",
    implies: ["CRM.DEALS.VIEW"],
    description: "Modify the monetary value of a deal.",
  },
  {
    key: "CRM.DEALS.EXPORT",
    bit: 106,
    module: "CRM" as const,
    submodule: "Deals",
    action: "EXPORT",
    label: "Export deals",
    description: "Download deal data.",
  },
] as const;

const CRM_PIPELINES = [
  {
    key: "CRM.PIPELINES.VIEW",
    bit: 107,
    module: "CRM" as const,
    submodule: "Pipelines",
    action: "VIEW",
    label: "View pipelines",
    description: "See pipeline configurations and stages.",
  },
  {
    key: "CRM.PIPELINES.CREATE",
    bit: 108,
    module: "CRM" as const,
    submodule: "Pipelines",
    action: "CREATE",
    label: "Create pipelines",
    implies: ["CRM.PIPELINES.VIEW"],
    description: "Create new deal pipelines.",
  },
  {
    key: "CRM.PIPELINES.UPDATE",
    bit: 109,
    module: "CRM" as const,
    submodule: "Pipelines",
    action: "UPDATE",
    label: "Edit pipelines",
    implies: ["CRM.PIPELINES.VIEW"],
    description: "Modify pipeline stages and settings.",
  },
  {
    key: "CRM.PIPELINES.DELETE",
    bit: 110,
    module: "CRM" as const,
    submodule: "Pipelines",
    action: "DELETE",
    label: "Delete pipelines",
    dangerous: true,
    implies: ["CRM.PIPELINES.VIEW"],
    description: "Remove pipelines.",
  },
] as const;

const CRM_WORKFLOWS = [
  {
    key: "CRM.WORKFLOWS.VIEW",
    bit: 111,
    module: "CRM" as const,
    submodule: "Workflows",
    action: "VIEW",
    label: "View workflows",
    description: "See workflow automation configurations.",
  },
  {
    key: "CRM.WORKFLOWS.CREATE",
    bit: 112,
    module: "CRM" as const,
    submodule: "Workflows",
    action: "CREATE",
    label: "Create workflows",
    implies: ["CRM.WORKFLOWS.VIEW"],
    description: "Create new workflows.",
  },
  {
    key: "CRM.WORKFLOWS.UPDATE",
    bit: 113,
    module: "CRM" as const,
    submodule: "Workflows",
    action: "UPDATE",
    label: "Edit workflows",
    implies: ["CRM.WORKFLOWS.VIEW"],
    description: "Modify workflow definitions.",
  },
  {
    key: "CRM.WORKFLOWS.DELETE",
    bit: 114,
    module: "CRM" as const,
    submodule: "Workflows",
    action: "DELETE",
    label: "Delete workflows",
    dangerous: true,
    implies: ["CRM.WORKFLOWS.VIEW"],
    description: "Remove workflows.",
  },
  {
    key: "CRM.WORKFLOWS.EXECUTE",
    bit: 115,
    module: "CRM" as const,
    submodule: "Workflows",
    action: "EXECUTE",
    label: "Execute workflows",
    implies: ["CRM.WORKFLOWS.VIEW"],
    description: "Manually trigger workflow execution.",
  },
  {
    key: "CRM.WORKFLOWS.PAUSE",
    bit: 116,
    module: "CRM" as const,
    submodule: "Workflows",
    action: "PAUSE",
    label: "Pause workflows",
    implies: ["CRM.WORKFLOWS.VIEW"],
    description: "Temporarily disable active workflows.",
  },
] as const;

const CRM_TASKS = [
  {
    key: "CRM.TASKS.VIEW",
    bit: 117,
    module: "CRM" as const,
    submodule: "Tasks",
    action: "VIEW",
    label: "View tasks",
    description: "See task list and details.",
  },
  {
    key: "CRM.TASKS.VIEW_OWN_ONLY",
    bit: 118,
    module: "CRM" as const,
    submodule: "Tasks",
    action: "VIEW_OWN_ONLY",
    label: "View only own tasks",
    description: "See only tasks assigned to the user.",
  },
  {
    key: "CRM.TASKS.CREATE",
    bit: 119,
    module: "CRM" as const,
    submodule: "Tasks",
    action: "CREATE",
    label: "Create tasks",
    implies: ["CRM.TASKS.VIEW"],
    description: "Create new tasks.",
  },
  {
    key: "CRM.TASKS.UPDATE",
    bit: 120,
    module: "CRM" as const,
    submodule: "Tasks",
    action: "UPDATE",
    label: "Edit tasks",
    implies: ["CRM.TASKS.VIEW"],
    description: "Modify task details.",
  },
  {
    key: "CRM.TASKS.DELETE",
    bit: 121,
    module: "CRM" as const,
    submodule: "Tasks",
    action: "DELETE",
    label: "Delete tasks",
    dangerous: true,
    implies: ["CRM.TASKS.VIEW"],
    description: "Remove tasks.",
  },
  {
    key: "CRM.TASKS.ASSIGN",
    bit: 122,
    module: "CRM" as const,
    submodule: "Tasks",
    action: "ASSIGN",
    label: "Assign tasks",
    implies: ["CRM.TASKS.VIEW"],
    description: "Assign tasks to team members.",
  },
  {
    key: "CRM.TASKS.COMPLETE_OTHERS",
    bit: 123,
    module: "CRM" as const,
    submodule: "Tasks",
    action: "COMPLETE_OTHERS",
    label: "Complete others tasks",
    implies: ["CRM.TASKS.VIEW"],
    description: "Mark tasks completed by other users as done.",
  },
] as const;

const CRM_ACTIVITIES = [
  {
    key: "CRM.ACTIVITIES.VIEW",
    bit: 124,
    module: "CRM" as const,
    submodule: "Activities",
    action: "VIEW",
    label: "View activities",
    description: "See activity history and logs.",
  },
  {
    key: "CRM.ACTIVITIES.CREATE",
    bit: 125,
    module: "CRM" as const,
    submodule: "Activities",
    action: "CREATE",
    label: "Create activities",
    implies: ["CRM.ACTIVITIES.VIEW"],
    description: "Log new activities (calls, emails, meetings).",
  },
  {
    key: "CRM.ACTIVITIES.UPDATE",
    bit: 126,
    module: "CRM" as const,
    submodule: "Activities",
    action: "UPDATE",
    label: "Edit activities",
    implies: ["CRM.ACTIVITIES.VIEW"],
    description: "Modify activity details.",
  },
  {
    key: "CRM.ACTIVITIES.DELETE",
    bit: 127,
    module: "CRM" as const,
    submodule: "Activities",
    action: "DELETE",
    label: "Delete activities",
    dangerous: true,
    implies: ["CRM.ACTIVITIES.VIEW"],
    description: "Remove activities from history.",
  },
] as const;

const CRM_AUTOMATIONS = [
  {
    key: "CRM.AUTOMATIONS.VIEW",
    bit: 128,
    module: "CRM" as const,
    submodule: "Automations",
    action: "VIEW",
    label: "View automations",
    description: "See automation configurations.",
  },
  {
    key: "CRM.AUTOMATIONS.CREATE",
    bit: 129,
    module: "CRM" as const,
    submodule: "Automations",
    action: "CREATE",
    label: "Create automations",
    implies: ["CRM.AUTOMATIONS.VIEW"],
    description: "Create new automations.",
  },
  {
    key: "CRM.AUTOMATIONS.UPDATE",
    bit: 130,
    module: "CRM" as const,
    submodule: "Automations",
    action: "UPDATE",
    label: "Edit automations",
    implies: ["CRM.AUTOMATIONS.VIEW"],
    description: "Modify automation rules.",
  },
  {
    key: "CRM.AUTOMATIONS.DELETE",
    bit: 131,
    module: "CRM" as const,
    submodule: "Automations",
    action: "DELETE",
    label: "Delete automations",
    dangerous: true,
    implies: ["CRM.AUTOMATIONS.VIEW"],
    description: "Remove automations.",
  },
  {
    key: "CRM.AUTOMATIONS.ENABLE",
    bit: 132,
    module: "CRM" as const,
    submodule: "Automations",
    action: "ENABLE",
    label: "Enable automations",
    implies: ["CRM.AUTOMATIONS.VIEW"],
    description: "Activate automations.",
  },
  {
    key: "CRM.AUTOMATIONS.DISABLE",
    bit: 133,
    module: "CRM" as const,
    submodule: "Automations",
    action: "DISABLE",
    label: "Disable automations",
    implies: ["CRM.AUTOMATIONS.VIEW"],
    description: "Deactivate automations.",
  },
  {
    key: "CRM.AUTOMATIONS.RUN_NOW",
    bit: 134,
    module: "CRM" as const,
    submodule: "Automations",
    action: "RUN_NOW",
    label: "Run automations manually",
    implies: ["CRM.AUTOMATIONS.VIEW"],
    description: "Trigger automations immediately.",
  },
] as const;

const CRM_REMARKETING = [
  {
    key: "CRM.REMARKETING.VIEW",
    bit: 135,
    module: "CRM" as const,
    submodule: "Remarketing",
    action: "VIEW",
    label: "View remarketing campaigns",
    description: "See remarketing campaign configurations.",
  },
  {
    key: "CRM.REMARKETING.CREATE",
    bit: 136,
    module: "CRM" as const,
    submodule: "Remarketing",
    action: "CREATE",
    label: "Create remarketing",
    implies: ["CRM.REMARKETING.VIEW"],
    description: "Create remarketing campaigns.",
  },
  {
    key: "CRM.REMARKETING.UPDATE",
    bit: 137,
    module: "CRM" as const,
    submodule: "Remarketing",
    action: "UPDATE",
    label: "Edit remarketing",
    implies: ["CRM.REMARKETING.VIEW"],
    description: "Modify remarketing campaigns.",
  },
  {
    key: "CRM.REMARKETING.DELETE",
    bit: 138,
    module: "CRM" as const,
    submodule: "Remarketing",
    action: "DELETE",
    label: "Delete remarketing",
    dangerous: true,
    implies: ["CRM.REMARKETING.VIEW"],
    description: "Remove remarketing campaigns.",
  },
] as const;

const CRM_CONTACT_NOTES = [
  {
    key: "CRM.CONTACT_NOTES.VIEW",
    bit: 139,
    module: "CRM" as const,
    submodule: "Contact Notes",
    action: "VIEW",
    label: "View contact notes",
    description: "See notes on contact records.",
  },
  {
    key: "CRM.CONTACT_NOTES.CREATE",
    bit: 140,
    module: "CRM" as const,
    submodule: "Contact Notes",
    action: "CREATE",
    label: "Create notes",
    implies: ["CRM.CONTACT_NOTES.VIEW"],
    description: "Add notes to contacts.",
  },
  {
    key: "CRM.CONTACT_NOTES.UPDATE",
    bit: 141,
    module: "CRM" as const,
    submodule: "Contact Notes",
    action: "UPDATE",
    label: "Edit notes",
    implies: ["CRM.CONTACT_NOTES.VIEW"],
    description: "Modify contact notes.",
  },
  {
    key: "CRM.CONTACT_NOTES.DELETE",
    bit: 142,
    module: "CRM" as const,
    submodule: "Contact Notes",
    action: "DELETE",
    label: "Delete notes",
    dangerous: true,
    implies: ["CRM.CONTACT_NOTES.VIEW"],
    description: "Remove contact notes.",
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// WEBSITE MODULE (Bits 143–230)
// ─────────────────────────────────────────────────────────────────────────────

const WEBSITE_BLOG = [
  {
    key: "WEBSITE.BLOG.VIEW",
    bit: 143,
    module: "WEBSITE" as const,
    submodule: "Blog",
    action: "VIEW",
    label: "View blog posts",
    description: "See blog post list and content.",
  },
  {
    key: "WEBSITE.BLOG.CREATE",
    bit: 144,
    module: "WEBSITE" as const,
    submodule: "Blog",
    action: "CREATE",
    label: "Create blog posts",
    implies: ["WEBSITE.BLOG.VIEW"],
    description: "Write new blog posts.",
  },
  {
    key: "WEBSITE.BLOG.UPDATE",
    bit: 145,
    module: "WEBSITE" as const,
    submodule: "Blog",
    action: "UPDATE",
    label: "Edit blog posts",
    implies: ["WEBSITE.BLOG.VIEW"],
    description: "Modify blog posts.",
  },
  {
    key: "WEBSITE.BLOG.DELETE",
    bit: 146,
    module: "WEBSITE" as const,
    submodule: "Blog",
    action: "DELETE",
    label: "Delete blog posts",
    dangerous: true,
    implies: ["WEBSITE.BLOG.VIEW"],
    description: "Remove blog posts.",
  },
  {
    key: "WEBSITE.BLOG.PUBLISH",
    bit: 147,
    module: "WEBSITE" as const,
    submodule: "Blog",
    action: "PUBLISH",
    label: "Publish blog posts",
    implies: ["WEBSITE.BLOG.VIEW"],
    description: "Make blog posts live.",
  },
] as const;

const WEBSITE_PAGES = [
  {
    key: "WEBSITE.PAGES.VIEW",
    bit: 148,
    module: "WEBSITE" as const,
    submodule: "Pages",
    action: "VIEW",
    label: "View pages",
    description: "See website pages.",
  },
  {
    key: "WEBSITE.PAGES.CREATE",
    bit: 149,
    module: "WEBSITE" as const,
    submodule: "Pages",
    action: "CREATE",
    label: "Create pages",
    implies: ["WEBSITE.PAGES.VIEW"],
    description: "Create new website pages.",
  },
  {
    key: "WEBSITE.PAGES.UPDATE",
    bit: 150,
    module: "WEBSITE" as const,
    submodule: "Pages",
    action: "UPDATE",
    label: "Edit pages",
    implies: ["WEBSITE.PAGES.VIEW"],
    description: "Modify page content.",
  },
  {
    key: "WEBSITE.PAGES.DELETE",
    bit: 151,
    module: "WEBSITE" as const,
    submodule: "Pages",
    action: "DELETE",
    label: "Delete pages",
    dangerous: true,
    implies: ["WEBSITE.PAGES.VIEW"],
    description: "Remove pages.",
  },
  {
    key: "WEBSITE.PAGES.PUBLISH",
    bit: 152,
    module: "WEBSITE" as const,
    submodule: "Pages",
    action: "PUBLISH",
    label: "Publish pages",
    implies: ["WEBSITE.PAGES.VIEW"],
    description: "Make pages live.",
  },
] as const;

const WEBSITE_SITE = [
  {
    key: "WEBSITE.SITE.VIEW",
    bit: 153,
    module: "WEBSITE" as const,
    submodule: "Site",
    action: "VIEW",
    label: "View site settings",
    description: "See website configuration.",
  },
  {
    key: "WEBSITE.SITE.UPDATE",
    bit: 154,
    module: "WEBSITE" as const,
    submodule: "Site",
    action: "UPDATE",
    label: "Edit site settings",
    implies: ["WEBSITE.SITE.VIEW"],
    description: "Modify website configuration.",
  },
  {
    key: "WEBSITE.SITE.DEPLOY",
    bit: 155,
    module: "WEBSITE" as const,
    submodule: "Site",
    action: "DEPLOY",
    label: "Deploy website",
    dangerous: true,
    implies: ["WEBSITE.SITE.VIEW"],
    description: "Publish changes to the live website.",
  },
] as const;

const WEBSITE_MEDIA = [
  {
    key: "WEBSITE.MEDIA.VIEW",
    bit: 156,
    module: "WEBSITE" as const,
    submodule: "Media",
    action: "VIEW",
    label: "View media",
    description: "See media library.",
  },
  {
    key: "WEBSITE.MEDIA.CREATE",
    bit: 157,
    module: "WEBSITE" as const,
    submodule: "Media",
    action: "CREATE",
    label: "Upload media",
    implies: ["WEBSITE.MEDIA.VIEW"],
    description: "Upload images and documents.",
  },
  {
    key: "WEBSITE.MEDIA.UPDATE",
    bit: 158,
    module: "WEBSITE" as const,
    submodule: "Media",
    action: "UPDATE",
    label: "Edit media",
    implies: ["WEBSITE.MEDIA.VIEW"],
    description: "Modify media metadata.",
  },
  {
    key: "WEBSITE.MEDIA.DELETE",
    bit: 159,
    module: "WEBSITE" as const,
    submodule: "Media",
    action: "DELETE",
    label: "Delete media",
    dangerous: true,
    implies: ["WEBSITE.MEDIA.VIEW"],
    description: "Remove media files.",
  },
  {
    key: "WEBSITE.MEDIA.DELETE_OTHERS",
    bit: 160,
    module: "WEBSITE" as const,
    submodule: "Media",
    action: "DELETE_OTHERS",
    label: "Delete others media",
    dangerous: true,
    implies: ["WEBSITE.MEDIA.VIEW"],
    description: "Delete media uploaded by other users.",
  },
] as const;

const WEBSITE_REVIEWS = [
  {
    key: "WEBSITE.REVIEWS.VIEW",
    bit: 161,
    module: "WEBSITE" as const,
    submodule: "Reviews",
    action: "VIEW",
    label: "View reviews",
    description: "See customer reviews and ratings.",
  },
  {
    key: "WEBSITE.REVIEWS.APPROVE",
    bit: 162,
    module: "WEBSITE" as const,
    submodule: "Reviews",
    action: "APPROVE",
    label: "Approve reviews",
    implies: ["WEBSITE.REVIEWS.VIEW"],
    description: "Approve reviews for publication.",
  },
  {
    key: "WEBSITE.REVIEWS.REJECT",
    bit: 163,
    module: "WEBSITE" as const,
    submodule: "Reviews",
    action: "REJECT",
    label: "Reject reviews",
    implies: ["WEBSITE.REVIEWS.VIEW"],
    description: "Reject inappropriate reviews.",
  },
  {
    key: "WEBSITE.REVIEWS.REPLY",
    bit: 164,
    module: "WEBSITE" as const,
    submodule: "Reviews",
    action: "REPLY",
    label: "Reply to reviews",
    implies: ["WEBSITE.REVIEWS.VIEW"],
    description: "Respond to customer reviews.",
  },
  {
    key: "WEBSITE.REVIEWS.DELETE",
    bit: 165,
    module: "WEBSITE" as const,
    submodule: "Reviews",
    action: "DELETE",
    label: "Delete reviews",
    dangerous: true,
    implies: ["WEBSITE.REVIEWS.VIEW"],
    description: "Remove reviews.",
  },
] as const;

const WEBSITE_NAV_MENUS = [
  {
    key: "WEBSITE.NAV_MENUS.VIEW",
    bit: 166,
    module: "WEBSITE" as const,
    submodule: "Nav Menus",
    action: "VIEW",
    label: "View navigation menus",
    description: "See website navigation configurations.",
  },
  {
    key: "WEBSITE.NAV_MENUS.CREATE",
    bit: 167,
    module: "WEBSITE" as const,
    submodule: "Nav Menus",
    action: "CREATE",
    label: "Create nav menus",
    implies: ["WEBSITE.NAV_MENUS.VIEW"],
    description: "Create navigation menus.",
  },
  {
    key: "WEBSITE.NAV_MENUS.UPDATE",
    bit: 168,
    module: "WEBSITE" as const,
    submodule: "Nav Menus",
    action: "UPDATE",
    label: "Edit nav menus",
    implies: ["WEBSITE.NAV_MENUS.VIEW"],
    description: "Modify navigation menus.",
  },
  {
    key: "WEBSITE.NAV_MENUS.DELETE",
    bit: 169,
    module: "WEBSITE" as const,
    submodule: "Nav Menus",
    action: "DELETE",
    label: "Delete nav menus",
    dangerous: true,
    implies: ["WEBSITE.NAV_MENUS.VIEW"],
    description: "Remove navigation menus.",
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// REPORTS MODULE (Bits 170–199)
// ─────────────────────────────────────────────────────────────────────────────

const REPORTS_ANALYTICS = [
  {
    key: "REPORTS.ANALYTICS.VIEW",
    bit: 170,
    module: "REPORTS" as const,
    submodule: "Analytics",
    action: "VIEW",
    label: "View analytics",
    description: "See analytics dashboards and reports.",
  },
  {
    key: "REPORTS.ANALYTICS.VIEW_REVENUE_PII",
    bit: 171,
    module: "REPORTS" as const,
    submodule: "Analytics",
    action: "VIEW_REVENUE_PII",
    label: "View revenue analytics",
    implies: ["REPORTS.ANALYTICS.VIEW"],
    description: "View sensitive revenue data.",
  },
  {
    key: "REPORTS.ANALYTICS.EXPORT",
    bit: 172,
    module: "REPORTS" as const,
    submodule: "Analytics",
    action: "EXPORT",
    label: "Export analytics",
    description: "Download analytics data.",
  },
] as const;

const REPORTS_DASHBOARDS = [
  {
    key: "REPORTS.DASHBOARDS.VIEW",
    bit: 173,
    module: "REPORTS" as const,
    submodule: "Dashboards",
    action: "VIEW",
    label: "View dashboards",
    description: "See custom dashboards.",
  },
  {
    key: "REPORTS.DASHBOARDS.CREATE",
    bit: 174,
    module: "REPORTS" as const,
    submodule: "Dashboards",
    action: "CREATE",
    label: "Create dashboards",
    implies: ["REPORTS.DASHBOARDS.VIEW"],
    description: "Build custom dashboards.",
  },
  {
    key: "REPORTS.DASHBOARDS.UPDATE",
    bit: 175,
    module: "REPORTS" as const,
    submodule: "Dashboards",
    action: "UPDATE",
    label: "Edit dashboards",
    implies: ["REPORTS.DASHBOARDS.VIEW"],
    description: "Modify dashboards.",
  },
  {
    key: "REPORTS.DASHBOARDS.DELETE",
    bit: 176,
    module: "REPORTS" as const,
    submodule: "Dashboards",
    action: "DELETE",
    label: "Delete dashboards",
    dangerous: true,
    implies: ["REPORTS.DASHBOARDS.VIEW"],
    description: "Remove dashboards.",
  },
  {
    key: "REPORTS.DASHBOARDS.SHARE",
    bit: 177,
    module: "REPORTS" as const,
    submodule: "Dashboards",
    action: "SHARE",
    label: "Share dashboards",
    implies: ["REPORTS.DASHBOARDS.VIEW"],
    description: "Share dashboards with other users.",
  },
] as const;

const REPORTS_CUSTOM = [
  {
    key: "REPORTS.CUSTOM_REPORTS.VIEW",
    bit: 178,
    module: "REPORTS" as const,
    submodule: "Custom Reports",
    action: "VIEW",
    label: "View custom reports",
    description: "See custom reports.",
  },
  {
    key: "REPORTS.CUSTOM_REPORTS.CREATE",
    bit: 179,
    module: "REPORTS" as const,
    submodule: "Custom Reports",
    action: "CREATE",
    label: "Create reports",
    implies: ["REPORTS.CUSTOM_REPORTS.VIEW"],
    description: "Build custom reports.",
  },
  {
    key: "REPORTS.CUSTOM_REPORTS.UPDATE",
    bit: 180,
    module: "REPORTS" as const,
    submodule: "Custom Reports",
    action: "UPDATE",
    label: "Edit reports",
    implies: ["REPORTS.CUSTOM_REPORTS.VIEW"],
    description: "Modify reports.",
  },
  {
    key: "REPORTS.CUSTOM_REPORTS.DELETE",
    bit: 181,
    module: "REPORTS" as const,
    submodule: "Custom Reports",
    action: "DELETE",
    label: "Delete reports",
    dangerous: true,
    implies: ["REPORTS.CUSTOM_REPORTS.VIEW"],
    description: "Remove reports.",
  },
  {
    key: "REPORTS.CUSTOM_REPORTS.SCHEDULE",
    bit: 182,
    module: "REPORTS" as const,
    submodule: "Custom Reports",
    action: "SCHEDULE",
    label: "Schedule reports",
    implies: ["REPORTS.CUSTOM_REPORTS.VIEW"],
    description: "Schedule automated report delivery.",
  },
  {
    key: "REPORTS.CUSTOM_REPORTS.EXPORT",
    bit: 183,
    module: "REPORTS" as const,
    submodule: "Custom Reports",
    action: "EXPORT",
    label: "Export reports",
    description: "Download report data.",
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// SETTINGS MODULE (Bits 184–510)
// ─────────────────────────────────────────────────────────────────────────────

const SETTINGS_USERS = [
  {
    key: "SETTINGS.USERS.VIEW",
    bit: 184,
    module: "SETTINGS" as const,
    submodule: "Users",
    action: "VIEW",
    label: "View users",
    description: "See user list and profiles.",
  },
  {
    key: "SETTINGS.USERS.CREATE",
    bit: 185,
    module: "SETTINGS" as const,
    submodule: "Users",
    action: "CREATE",
    label: "Create users",
    implies: ["SETTINGS.USERS.VIEW"],
    description: "Add new user accounts.",
  },
  {
    key: "SETTINGS.USERS.UPDATE",
    bit: 186,
    module: "SETTINGS" as const,
    submodule: "Users",
    action: "UPDATE",
    label: "Edit users",
    implies: ["SETTINGS.USERS.VIEW"],
    description: "Modify user profiles.",
  },
  {
    key: "SETTINGS.USERS.DELETE",
    bit: 187,
    module: "SETTINGS" as const,
    submodule: "Users",
    action: "DELETE",
    label: "Delete users",
    dangerous: true,
    implies: ["SETTINGS.USERS.VIEW"],
    description: "Remove user accounts.",
  },
  {
    key: "SETTINGS.USERS.RESET_PASSWORD",
    bit: 188,
    module: "SETTINGS" as const,
    submodule: "Users",
    action: "RESET_PASSWORD",
    label: "Reset user passwords",
    implies: ["SETTINGS.USERS.VIEW"],
    description: "Reset another users password.",
  },
  {
    key: "SETTINGS.USERS.FORCE_LOGOUT",
    bit: 189,
    module: "SETTINGS" as const,
    submodule: "Users",
    action: "FORCE_LOGOUT",
    label: "Force user logout",
    dangerous: true,
    implies: ["SETTINGS.USERS.VIEW"],
    description: "Force a user to log out of all sessions.",
  },
] as const;

const SETTINGS_ROLES = [
  {
    key: "SETTINGS.ROLES.VIEW",
    bit: 190,
    module: "SETTINGS" as const,
    submodule: "Roles",
    action: "VIEW",
    label: "View roles",
    description: "See role list and configurations.",
  },
  {
    key: "SETTINGS.ROLES.CREATE",
    bit: 191,
    module: "SETTINGS" as const,
    submodule: "Roles",
    action: "CREATE",
    label: "Create roles",
    implies: ["SETTINGS.ROLES.VIEW"],
    description: "Create new roles.",
  },
  {
    key: "SETTINGS.ROLES.UPDATE",
    bit: 192,
    module: "SETTINGS" as const,
    submodule: "Roles",
    action: "UPDATE",
    label: "Edit roles",
    implies: ["SETTINGS.ROLES.VIEW"],
    description: "Modify role permissions.",
  },
  {
    key: "SETTINGS.ROLES.DELETE",
    bit: 193,
    module: "SETTINGS" as const,
    submodule: "Roles",
    action: "DELETE",
    label: "Delete roles",
    dangerous: true,
    implies: ["SETTINGS.ROLES.VIEW"],
    description: "Remove custom roles.",
  },
  {
    key: "SETTINGS.ROLES.ASSIGN",
    bit: 194,
    module: "SETTINGS" as const,
    submodule: "Roles",
    action: "ASSIGN",
    label: "Assign roles",
    implies: ["SETTINGS.ROLES.VIEW"],
    description: "Assign roles to users.",
  },
  {
    key: "SETTINGS.ROLES.MANAGE",
    bit: 195,
    module: "SETTINGS" as const,
    submodule: "Roles",
    action: "MANAGE",
    label: "Manage roles",
    implies: ["SETTINGS.ROLES.VIEW"],
    description: "Full role management including permission editing.",
  },
] as const;

const SETTINGS_MEMBERS = [
  {
    key: "SETTINGS.MEMBERS.VIEW",
    bit: 196,
    module: "SETTINGS" as const,
    submodule: "Members",
    action: "VIEW",
    label: "View members",
    description: "See tenant member list.",
  },
  {
    key: "SETTINGS.MEMBERS.CREATE",
    bit: 197,
    module: "SETTINGS" as const,
    submodule: "Members",
    action: "CREATE",
    label: "Invite members",
    implies: ["SETTINGS.MEMBERS.VIEW"],
    description: "Invite new team members.",
  },
  {
    key: "SETTINGS.MEMBERS.UPDATE",
    bit: 198,
    module: "SETTINGS" as const,
    submodule: "Members",
    action: "UPDATE",
    label: "Edit member info",
    implies: ["SETTINGS.MEMBERS.VIEW"],
    description: "Modify member details.",
  },
  {
    key: "SETTINGS.MEMBERS.REVOKE",
    bit: 199,
    module: "SETTINGS" as const,
    submodule: "Members",
    action: "REVOKE",
    label: "Remove members",
    dangerous: true,
    implies: ["SETTINGS.MEMBERS.VIEW"],
    description: "Revoke member access.",
  },
] as const;

const SETTINGS_TENANT = [
  {
    key: "SETTINGS.TENANT.VIEW",
    bit: 200,
    module: "SETTINGS" as const,
    submodule: "Tenant",
    action: "VIEW",
    label: "View tenant settings",
    description: "See tenant configuration.",
  },
  {
    key: "SETTINGS.TENANT.UPDATE_BRANDING",
    bit: 201,
    module: "SETTINGS" as const,
    submodule: "Tenant",
    action: "UPDATE_BRANDING",
    label: "Update branding",
    implies: ["SETTINGS.TENANT.VIEW"],
    description: "Change company name, logo, and branding.",
  },
  {
    key: "SETTINGS.TENANT.UPDATE_PLAN",
    bit: 202,
    module: "SETTINGS" as const,
    submodule: "Tenant",
    action: "UPDATE_PLAN",
    label: "Change plan",
    dangerous: true,
    implies: ["SETTINGS.TENANT.VIEW"],
    description: "Modify subscription plan and billing.",
  },
] as const;

const SETTINGS_AUDIT = [
  {
    key: "SETTINGS.AUDIT.VIEW",
    bit: 203,
    module: "SETTINGS" as const,
    submodule: "Audit",
    action: "VIEW",
    label: "View audit logs",
    description: "See activity and change logs.",
  },
  {
    key: "SETTINGS.AUDIT.EXPORT",
    bit: 204,
    module: "SETTINGS" as const,
    submodule: "Audit",
    action: "EXPORT",
    label: "Export audit logs",
    description: "Download audit logs.",
  },
  {
    key: "SETTINGS.AUDIT.PURGE",
    bit: 205,
    module: "SETTINGS" as const,
    submodule: "Audit",
    action: "PURGE",
    label: "Purge audit logs",
    dangerous: true,
    implies: ["SETTINGS.AUDIT.VIEW"],
    description: "Delete audit logs permanently.",
  },
] as const;

const SETTINGS_TRASH = [
  {
    key: "SETTINGS.TRASH.VIEW",
    bit: 206,
    module: "SETTINGS" as const,
    submodule: "Trash",
    action: "VIEW",
    label: "View trash",
    description: "See deleted items.",
  },
  {
    key: "SETTINGS.TRASH.RESTORE",
    bit: 207,
    module: "SETTINGS" as const,
    submodule: "Trash",
    action: "RESTORE",
    label: "Restore from trash",
    implies: ["SETTINGS.TRASH.VIEW"],
    description: "Restore deleted items.",
  },
  {
    key: "SETTINGS.TRASH.PURGE",
    bit: 208,
    module: "SETTINGS" as const,
    submodule: "Trash",
    action: "PURGE",
    label: "Permanently delete",
    dangerous: true,
    implies: ["SETTINGS.TRASH.VIEW"],
    description: "Permanently delete items.",
  },
] as const;

const SETTINGS_ERROR_REPORTS = [
  {
    key: "SETTINGS.ERROR_REPORTS.VIEW",
    bit: 209,
    module: "SETTINGS" as const,
    submodule: "Error Reports",
    action: "VIEW",
    label: "View error reports",
    description: "See application error logs.",
  },
  {
    key: "SETTINGS.ERROR_REPORTS.EXPORT",
    bit: 210,
    module: "SETTINGS" as const,
    submodule: "Error Reports",
    action: "EXPORT",
    label: "Export error reports",
    description: "Download error reports.",
  },
  {
    key: "SETTINGS.ERROR_REPORTS.DELETE",
    bit: 211,
    module: "SETTINGS" as const,
    submodule: "Error Reports",
    action: "DELETE",
    label: "Delete error reports",
    dangerous: true,
    implies: ["SETTINGS.ERROR_REPORTS.VIEW"],
    description: "Clear error reports.",
  },
] as const;

const SETTINGS_DOMAINS = [
  {
    key: "SETTINGS.DOMAINS.VIEW",
    bit: 212,
    module: "SETTINGS" as const,
    submodule: "Domains",
    action: "VIEW",
    label: "View domains",
    description: "See configured custom domains.",
  },
  {
    key: "SETTINGS.DOMAINS.CREATE",
    bit: 213,
    module: "SETTINGS" as const,
    submodule: "Domains",
    action: "CREATE",
    label: "Add domains",
    implies: ["SETTINGS.DOMAINS.VIEW"],
    description: "Add new custom domains.",
  },
  {
    key: "SETTINGS.DOMAINS.UPDATE",
    bit: 214,
    module: "SETTINGS" as const,
    submodule: "Domains",
    action: "UPDATE",
    label: "Edit domains",
    implies: ["SETTINGS.DOMAINS.VIEW"],
    description: "Modify domain settings.",
  },
  {
    key: "SETTINGS.DOMAINS.DELETE",
    bit: 215,
    module: "SETTINGS" as const,
    submodule: "Domains",
    action: "DELETE",
    label: "Delete domains",
    dangerous: true,
    implies: ["SETTINGS.DOMAINS.VIEW"],
    description: "Remove custom domains.",
  },
] as const;

const SETTINGS_NOTIFICATIONS = [
  {
    key: "SETTINGS.NOTIFICATIONS.VIEW",
    bit: 216,
    module: "SETTINGS" as const,
    submodule: "Notifications",
    action: "VIEW",
    label: "View notification settings",
    description: "See notification preferences.",
  },
  {
    key: "SETTINGS.NOTIFICATIONS.UPDATE",
    bit: 217,
    module: "SETTINGS" as const,
    submodule: "Notifications",
    action: "UPDATE",
    label: "Update notifications",
    implies: ["SETTINGS.NOTIFICATIONS.VIEW"],
    description: "Modify notification preferences.",
  },
] as const;

const SETTINGS_MESSAGING = [
  {
    key: "SETTINGS.MESSAGING.VIEW",
    bit: 218,
    module: "SETTINGS" as const,
    submodule: "Messaging",
    action: "VIEW",
    label: "View messaging settings",
    description: "See messaging integrations.",
  },
  {
    key: "SETTINGS.MESSAGING.UPDATE",
    bit: 219,
    module: "SETTINGS" as const,
    submodule: "Messaging",
    action: "UPDATE",
    label: "Update messaging",
    implies: ["SETTINGS.MESSAGING.VIEW"],
    description: "Configure messaging integrations.",
  },
  {
    key: "SETTINGS.MESSAGING.SEND_BROADCAST",
    bit: 220,
    module: "SETTINGS" as const,
    submodule: "Messaging",
    action: "SEND_BROADCAST",
    label: "Send broadcast messages",
    implies: ["SETTINGS.MESSAGING.VIEW"],
    description: "Send messages to all users.",
  },
  {
    key: "SETTINGS.MESSAGING.DELETE_OTHERS",
    bit: 221,
    module: "SETTINGS" as const,
    submodule: "Messaging",
    action: "DELETE_OTHERS",
    label: "Delete others messages",
    dangerous: true,
    implies: ["SETTINGS.MESSAGING.VIEW"],
    description: "Delete messages sent by other users.",
  },
] as const;

const SETTINGS_WEBHOOKS = [
  {
    key: "SETTINGS.WEBHOOKS.VIEW",
    bit: 222,
    module: "SETTINGS" as const,
    submodule: "Webhooks",
    action: "VIEW",
    label: "View webhooks",
    description: "See webhook configurations.",
  },
  {
    key: "SETTINGS.WEBHOOKS.CREATE",
    bit: 223,
    module: "SETTINGS" as const,
    submodule: "Webhooks",
    action: "CREATE",
    label: "Create webhooks",
    implies: ["SETTINGS.WEBHOOKS.VIEW"],
    description: "Create webhook endpoints.",
  },
  {
    key: "SETTINGS.WEBHOOKS.UPDATE",
    bit: 224,
    module: "SETTINGS" as const,
    submodule: "Webhooks",
    action: "UPDATE",
    label: "Edit webhooks",
    implies: ["SETTINGS.WEBHOOKS.VIEW"],
    description: "Modify webhook settings.",
  },
  {
    key: "SETTINGS.WEBHOOKS.DELETE",
    bit: 225,
    module: "SETTINGS" as const,
    submodule: "Webhooks",
    action: "DELETE",
    label: "Delete webhooks",
    dangerous: true,
    implies: ["SETTINGS.WEBHOOKS.VIEW"],
    description: "Remove webhooks.",
  },
  {
    key: "SETTINGS.WEBHOOKS.TEST",
    bit: 226,
    module: "SETTINGS" as const,
    submodule: "Webhooks",
    action: "TEST",
    label: "Test webhooks",
    implies: ["SETTINGS.WEBHOOKS.VIEW"],
    description: "Test webhook delivery.",
  },
  {
    key: "SETTINGS.WEBHOOKS.ROTATE_SECRET",
    bit: 227,
    module: "SETTINGS" as const,
    submodule: "Webhooks",
    action: "ROTATE_SECRET",
    label: "Rotate webhook secrets",
    dangerous: true,
    implies: ["SETTINGS.WEBHOOKS.VIEW"],
    description: "Regenerate webhook signing keys.",
  },
] as const;

const SETTINGS_API_ACCESS = [
  {
    key: "SETTINGS.API_ACCESS.VIEW",
    bit: 228,
    module: "SETTINGS" as const,
    submodule: "API Access",
    action: "VIEW",
    label: "View API keys",
    description: "See API access configurations.",
  },
  {
    key: "SETTINGS.API_ACCESS.CREATE",
    bit: 229,
    module: "SETTINGS" as const,
    submodule: "API Access",
    action: "CREATE",
    label: "Create API keys",
    implies: ["SETTINGS.API_ACCESS.VIEW"],
    description: "Generate new API keys.",
  },
  {
    key: "SETTINGS.API_ACCESS.ROTATE_KEY",
    bit: 230,
    module: "SETTINGS" as const,
    submodule: "API Access",
    action: "ROTATE_KEY",
    label: "Rotate API keys",
    dangerous: true,
    implies: ["SETTINGS.API_ACCESS.VIEW"],
    description: "Regenerate API keys.",
  },
  {
    key: "SETTINGS.API_ACCESS.REVOKE_KEY",
    bit: 231,
    module: "SETTINGS" as const,
    submodule: "API Access",
    action: "REVOKE_KEY",
    label: "Revoke API keys",
    dangerous: true,
    implies: ["SETTINGS.API_ACCESS.VIEW"],
    description: "Deactivate API keys.",
  },
] as const;

const SETTINGS_INTEGRATIONS = [
  {
    key: "SETTINGS.INTEGRATIONS.VIEW",
    bit: 232,
    module: "SETTINGS" as const,
    submodule: "Integrations",
    action: "VIEW",
    label: "View integrations",
    description: "See third-party integrations.",
  },
  {
    key: "SETTINGS.INTEGRATIONS.CONNECT",
    bit: 233,
    module: "SETTINGS" as const,
    submodule: "Integrations",
    action: "CONNECT",
    label: "Connect integrations",
    implies: ["SETTINGS.INTEGRATIONS.VIEW"],
    description: "Authorize new integrations.",
  },
  {
    key: "SETTINGS.INTEGRATIONS.DISCONNECT",
    bit: 234,
    module: "SETTINGS" as const,
    submodule: "Integrations",
    action: "DISCONNECT",
    label: "Disconnect integrations",
    implies: ["SETTINGS.INTEGRATIONS.VIEW"],
    description: "Remove integrations.",
  },
] as const;

const SETTINGS_AI = [
  {
    key: "SETTINGS.AI.VIEW",
    bit: 235,
    module: "SETTINGS" as const,
    submodule: "AI Settings",
    action: "VIEW",
    label: "View AI settings",
    description: "See AI feature configuration.",
  },
  {
    key: "SETTINGS.AI.UPDATE",
    bit: 236,
    module: "SETTINGS" as const,
    submodule: "AI Settings",
    action: "UPDATE",
    label: "Update AI settings",
    implies: ["SETTINGS.AI.VIEW"],
    description: "Configure AI features.",
  },
] as const;

// ADMINISTRATOR is the last permission, pinned at bit 511
const SETTINGS_ADMINISTRATOR = [
  {
    key: "SETTINGS.ADMINISTRATOR",
    bit: 511,
    module: "SETTINGS" as const,
    submodule: "Administrator",
    action: "ADMINISTRATOR",
    label: "Administrator",
    description: "Bypass every permission check. Use sparingly.",
    dangerous: true,
  },
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// FINAL CATALOG
// ─────────────────────────────────────────────────────────────────────────────

export const PERMISSIONS = [
  ...INVENTORY_PRODUCTS,
  ...INVENTORY_CATEGORIES,
  ...INVENTORY_VENDORS,
  ...INVENTORY_LOCATIONS,
  ...INVENTORY_TRANSFERS,
  ...INVENTORY_BUNDLES,
  ...INVENTORY_GIFT_CARDS,
  ...INVENTORY_PROMOS,
  ...INVENTORY_COLLECTIONS,
  ...INVENTORY_ATTRIBUTE_TYPES,
  ...INVENTORY_DISCOUNTS,
  ...SALES_SALES,
  ...SALES_WEBSITE_ORDERS,
  ...SALES_ABANDONED_CARTS,
  ...CRM_CONTACTS,
  ...CRM_COMPANIES,
  ...CRM_LEADS,
  ...CRM_DEALS,
  ...CRM_PIPELINES,
  ...CRM_WORKFLOWS,
  ...CRM_TASKS,
  ...CRM_ACTIVITIES,
  ...CRM_AUTOMATIONS,
  ...CRM_REMARKETING,
  ...CRM_CONTACT_NOTES,
  ...WEBSITE_BLOG,
  ...WEBSITE_PAGES,
  ...WEBSITE_SITE,
  ...WEBSITE_MEDIA,
  ...WEBSITE_REVIEWS,
  ...WEBSITE_NAV_MENUS,
  ...REPORTS_ANALYTICS,
  ...REPORTS_DASHBOARDS,
  ...REPORTS_CUSTOM,
  ...SETTINGS_USERS,
  ...SETTINGS_ROLES,
  ...SETTINGS_MEMBERS,
  ...SETTINGS_TENANT,
  ...SETTINGS_AUDIT,
  ...SETTINGS_TRASH,
  ...SETTINGS_ERROR_REPORTS,
  ...SETTINGS_DOMAINS,
  ...SETTINGS_NOTIFICATIONS,
  ...SETTINGS_MESSAGING,
  ...SETTINGS_WEBHOOKS,
  ...SETTINGS_API_ACCESS,
  ...SETTINGS_INTEGRATIONS,
  ...SETTINGS_AI,
  ...SETTINGS_ADMINISTRATOR,
] as const;

// Self-test at module load: verify no duplicate bits or keys
(() => {
  const bits = new Set<number>();
  const keys = new Set<string>();
  for (const perm of PERMISSIONS) {
    if (bits.has(perm.bit)) {
      throw new Error(`Duplicate bit ${perm.bit}: ${perm.key}`);
    }
    if (keys.has(perm.key)) {
      throw new Error(`Duplicate key: ${perm.key}`);
    }
    bits.add(perm.bit);
    keys.add(perm.key);
  }
})();

// Derived lookups built at startup. Typed as PermissionDef so callers see the
// uniform interface (with optional `implies`/`dangerous`) instead of the
// narrow per-entry literal union TS would otherwise infer.
export const PERMISSION_BY_KEY: ReadonlyMap<string, PermissionDef> = new Map(
  PERMISSIONS.map((p): [string, PermissionDef] => [p.key, p as PermissionDef]),
);
export const PERMISSION_BY_BIT: ReadonlyMap<number, PermissionDef> = new Map(
  PERMISSIONS.map((p): [number, PermissionDef] => [p.bit, p as PermissionDef]),
);

function groupBy<T, K extends string | number>(
  items: readonly T[],
  keyFn: (item: T) => K,
): Record<K, T[]> {
  const result = {} as Record<K, T[]>;
  for (const item of items) {
    const key = keyFn(item);
    if (!result[key]) result[key] = [];
    result[key].push(item);
  }
  return result;
}

export const PERMISSIONS_BY_MODULE = groupBy(PERMISSIONS, (p) => p.module);
export const PERMISSIONS_BY_SUBMODULE = groupBy(
  PERMISSIONS,
  (p) => `${p.module}::${p.submodule}` as any,
);

export const ADMINISTRATOR_BIT = PERMISSION_BY_KEY.get(
  "SETTINGS.ADMINISTRATOR",
)!.bit;
